### ISSUE TITLE
Colors as Computed Properties

### ISSUE THREAD

**Issue by Gatada** [fernandodelrio/SwiftColorGen#12]
I would prefer seeing the generated colours added as computed properties, as we are simply accessing a defined value of a particular type - and not doing any functional computation or state changing.

**Comment by fernandodelrio** [comment]
I like the idea. Something like:

```swift
extension UIColor {
    /// Color #FFC034 (alpha 255)
    static var myColor: UIColor {
        return UIColor(named: "MyColor") ?? .clear
    }
}
```

Accessing like:

```swift
UIColor.myColor
```

I will implement it 👍

**Comment by fernandodelrio** [comment]
Done on [0.5.1](https://github.com/fernandodelrio/SwiftColorGen/releases/tag/0.5.1)
